### ISSUE TITLE
fail to run centurylink / panamax-ui from docker hub

### ISSUE THREAD

**Issue by chaopeng** [CenturyLinkLabs/panamax-ui#505]
```
root@cdfe6c4e1882:/usr/src/app# rails s
=> Booting Puma
=> Rails 4.1.7 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/usr/local/lib/ruby/2.1.0/uri/generic.rb:214:in `initialize': the scheme http does not accept registry part: : (or bad hostname?) (URI::InvalidURIError)
	from /usr/local/lib/ruby/2.1.0/uri/http.rb:84:in `initialize'
	from /usr/local/lib/ruby/2.1.0/uri/common.rb:214:in `new'
	from /usr/local/lib/ruby/2.1.0/uri/common.rb:214:in `parse'
	from /usr/local/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:1009:in `create_site_uri_from'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:448:in `site='
	from /usr/src/app/app/models/base_resource.rb:7:in `<class:BaseResource>'
	from /usr/src/app/app/models/base_resource.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:348:in `require_or_load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:480:in `load_missing_constant'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:180:in `const_missing'
	from /usr/src/app/app/models/template.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:348:in `require_or_load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:480:in `load_missing_constant'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:180:in `const_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:512:in `load_missing_constant'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:180:in `const_missing'
	from /usr/src/app/app/controllers/deployments_controller.rb:5:in `<class:DeploymentsController>'
	from /usr/src/app/app/controllers/deployments_controller.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:348:in `require_or_load'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:307:in `depend_on'
	from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:225:in `require_dependency'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:467:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:467:in `block in eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:465:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:465:in `eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:346:in `eager_load!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/application/finisher.rb:58:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:300:in `initialize!'
	from /usr/src/app/config/environment.rb:5:in `<top (required)>'
	from /usr/src/app/config.ru:3:in `require'
	from /usr/src/app/config.ru:3:in `block in <main>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /usr/src/app/config.ru:in `new'
	from /usr/src/app/config.ru:in `<main>'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/server.rb:50:in `app'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
	from /usr/local/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/server.rb:69:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by chaopeng** [comment]
forgot `export PMX_API_PORT_3000_TCP_ADDR=localhost` in dockerfile

**Comment by tmadge** [comment]
+1

**Comment by patocox** [comment]
Are you guys doing a docker run command straight from docker hub? This image is meant to be used with Panamax (with cAdvisor and Panamax-API). You can find installation instructions here: https://github.com/CenturyLinkLabs/panamax-ui/wiki/Installing-Panamax

**Comment by rupakg** [comment]
@chaopeng @tmadge Panamax UI container needs the Panamax API and the cAdvisor containers to be running. They need to be linked with the API, and expose certain API endpoints that the UI container uses. Checkout the Panamax installation script code (https://github.com/CenturyLinkLabs/panamax-coreos/blob/master/coreos#L160-L175) to see how we run them.

**Comment by rossjimenez** [comment]
Closing
