### ISSUE TITLE
End of File Reached

### ISSUE THREAD

**Issue by JulianKingman** [CenturyLinkLabs/panamax-ui#553]
I've set up a remote VPS (hosted through digital ocean, though I didn't use the digital ocean setup in panamax), and when I try to deploy to it I get an error "End of File Reached", and it fails. Ideas?

**Comment by svains** [comment]
I am having the same issue here. I am trying to deploy from local panamax VM to remote CoreOS cloud, where I have installed remote agent and set up remote deploy target successfully. This is log from inside of panamax VM, where an error occures, when I am running template deployment. Any ideas guys?

```
Dec 14 21:57:42 panamax-vm docker[1640]: Faraday::Error::ConnectionFailed (end of file reached):
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/openssl/buffering.rb:182:in `read_nonblock'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:1378:in `request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:853:in `start'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/2.1.0/net/http.rb:1369:in `request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:75:in `perform_request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/adapter/net_http.rb:38:in `call'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/request/encode_json.rb:23:in `call'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/request/authorization.rb:36:in `call'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/lib/ruby/gems/2.1.0/gems/faraday-0.8.9/lib/faraday/connection.rb:118:in `post'
Dec 14 21:57:42 panamax-vm docker[1640]: /usr/src/app/app/services/deployment_service.rb:25:in `block in create'
...
Dec 14 21:57:42 panamax-vm docker[1640]: I, [2015-12-14T21:57:42.593601 #41]  INFO -- : Completed 500 Internal Server Error in 266ms (Views: 0.6ms | ActiveRecord: 0.7ms)
Dec 14 21:57:42 panamax-vm docker[1722]: E, [2015-12-14T21:57:42.595350 #7] ERROR -- :
Dec 14 21:57:42 panamax-vm docker[1722]: ActiveResource::ServerError (end of file reached):
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:156:in `handle_response'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:123:in `request'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:106:in `block in post'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:216:in `with_auth'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/connection.rb:106:in `post'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:1435:in `block in create'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:1434:in `create'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/observing.rb:21:in `create_with_notifications'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:1224:in `block in save'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:1223:in `save'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/validations.rb:116:in `save_with_validation'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/observing.rb:21:in `save_with_notifications'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:806:in `block in create'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:806:in `tap'
Dec 14 21:57:42 panamax-vm docker[1722]: /usr/lib/ruby/gems/2.1.0/gems/activeresource-4.0.0/lib/active_resource/base.rb:806:in `create'
...
```
