### ISSUE TITLE
Can't download/run Panamax templates, error 757 (unexpected token)

### ISSUE THREAD

**Issue by jplsegers** [CenturyLinkLabs/panamax-ui#556]
Just the other day I installed Panamax on a coreos VM as per the instructions on Github. After some fiddling with socket mapping between the coreos VM and the panamax containers, I got Panamax running.

When I search for a template from the UI and run locally, an error occurs. the error message is "757: unexpected token at '404 page not found ' ". This error occurs for any template I select. Form the Panamax API log:

I, [2015-12-14T13:24:15.942431 #40]  INFO -- : Started POST "/apps.json" for 172.18.0.4 at 2015-12-14 13:24:15 +0000
I, [2015-12-14T13:24:15.946871 #40]  INFO -- : Processing by AppsController#create as JSON
I, [2015-12-14T13:24:15.948416 #40]  INFO -- :   Parameters: {"template_id"=>"47"}
W, [2015-12-14T13:24:15.950919 #40]  WARN -- : Can't verify CSRF token authenticity
E, [2015-12-14T13:24:16.099539 #40] ERROR -- :
JSON::ParserError (757: unexpected token at '404 page not found
'):
  /usr/lib/ruby/2.1.0/json/common.rb:155:in `parse'
  /usr/lib/ruby/2.1.0/json/common.rb:155:in `parse'
  /usr/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/request.rb:51:in `raise_error'
  /usr/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/request.rb:31:in `request'
  /usr/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/request.rb:11:in `block (2 levels) in <module:Request>'
  /usr/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/client/unit.rb:18:in `create_unit'
  /usr/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/client.rb:58:in `submit'
  /usr/src/app/app/services/service_manager.rb:21:in `submit'
  /usr/src/app/app/models/service.rb:62:in `submit'
  /usr/lib/ruby/gems/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/delegation.rb:46:in `each'
  /usr/lib/ruby/gems/2.1.0/gems/activerecord-4.1.7/lib/active_record/relation/delegation.rb:46:in `each'
  /usr/src/app/app/models/app.rb:10:in `run'
  /usr/src/app/app/controllers/apps_controller.rb:26:in `create'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/base.rb:189:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/rendering.rb:10:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:113:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:229:in `block in halting'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `block in instrument'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `instrument'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/activerecord-4.1.7/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/abstract_controller/base.rb:136:in `process'
  /usr/lib/ruby/gems/2.1.0/gems/actionview-4.1.7/lib/action_view/rendering.rb:30:in `process'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal.rb:196:in `dispatch'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/metal.rb:232:in `block in action'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:82:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:50:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/journey/router.rb:73:in `block in call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/journey/router.rb:59:in `each'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/journey/router.rb:59:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/routing/route_set.rb:678:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/flash.rb:254:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activerecord-4.1.7/lib/active_record/query_cache.rb:36:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/callbacks.rb:82:in `run_callbacks'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/rack/logger.rb:38:in `call_app'
  /usr/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/rack/logger.rb:20:in `block in call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/tagged_logging.rb:68:in `tagged'
  /usr/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/rack/logger.rb:20:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/engine.rb:514:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/application.rb:144:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:490:in `handle_request'
  /usr/lib/ruby/gems/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:361:in `process_client'
  /usr/lib/ruby/gems/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:254:in `block in run'
  /usr/lib/ruby/gems/2.1.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `call'
  /usr/lib/ruby/gems/2.1.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `block in spawn_thread'

I'm running the following images:
panamax-ui:latest, image ID d0dd00067267a416677ff930f4d686b235d7042fa4cc7f2395d6fe842f129385
panamax-api:latest, image ID 9ce76a84c63e1c0542734786994c0a6afbc301e70cd8a16a4af996c3010c5462

**Comment by tpaksu** [comment]
same here. what do we need to do?
